//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbPractice.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public int serial { get; set; }
        public string name { get; set; }
        public string id { get; set; }
        public double cgpa { get; set; }
        public int age { get; set; }
    }
}
